language: go

go:
  - 1.7.4
  - 1.7.5
  - 1.8
  - tip

sudo: false

# env:
#   - GO15VENDOREXPERIMENT=1

install:
  - go get -v -t -d github.com/wojtekzw/statsdaemon/...

script:
  - go test -v -bench . $(go list github.com/wojtekzw/statsdaemon/... | grep -v vendor | grep -v tools)